### ISSUE TITLE
Wrong path when creating spec for lib/ directory file

### ISSUE THREAD

**Issue by patrykk21** [tatosjb/rspec-quick-spec#1]
Hello,
Amazing tool! Exactly what I was looking for :)

However when I launch the command for `models/user.rb` it works fine, but when I launch it for `lib/example.rb` it creates a spec in `lib/example_spec.rb`, however it should be `spec/lib/example_spec.rb`

LMK

Thank you :)

**Comment by patrykk21** [comment]
I believe the problem is here: https://github.com/tatosjb/rspec-quick-spec/blob/master/src/extension.ts#L20

We should check whether the path starts with 'spec', if it doesn't, prefix it! :)

**Comment by tatosjb** [comment]
Today I'll fix it

**Comment by tatosjb** [comment]
Solved on 853a6f02844005d50322af8125c898b90ebdb106
